language: haskell

ghc:
  - 7.8

install:
  - sudo apt-get update
  - sudo apt-get install zookeeperd 
  - cabal update
  - cabal install -j --only-dep  --enable-tests --force-reinstalls

script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test

after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls --exclude-dir=tests test
